// easy-rent-client-react/src/containers/identity/Login.tsx
const Login = () => {
    return (
        <form id="account" method="post">
            <h4>Use a local account to log in</h4>
            <hr />
            <div className="text-danger validation-summary-valid" data-valmsg-summary="true"><ul>
            </ul></div>
            <div className="form-group">
                <label htmlFor="Input_Email">Email</label>
                <input className="form-control" type="email" data-val="true" data-val-email="The Email field is not a valid e-mail address." data-val-required="The Email field is required." id="Input_Email" name="Input.Email" value="" />
                <span className="text-danger field-validation-valid" data-valmsg-htmlFor="Input.Email" data-valmsg-replace="true"></span>
            </div>
            <div className="form-group">
                <label htmlFor="Input_Password">Password</label>
                <input className="form-control" type="password" data-val="true" data-val-required="The Password field is required." id="Input_Password" name="Input.Password" />
                <span className="text-danger field-validation-valid" data-valmsg-htmlFor="Input.Password" data-valmsg-replace="true"></span>
            </div>
            <div className="form-group">
                <div className="checkbox">
                    <label htmlFor="Input_RememberMe">
                        <input type="checkbox" data-val="true" data-val-required="The Remember me? field is required." id="Input_RememberMe" name="Input.RememberMe" value="true" />
                    Remember me?
                </label>
                </div>
            </div>
            <div className="form-group">
                <button type="submit" className="btn btn-primary">Log in</button>
            </div>
        </form>
    );
}

export default Login;

// easy-rent-vue-client/src/views/identity/Login.vue
<template>
    <div class="row">
        <div class="col-sm-1 col-md-3"></div>
        <div class="col-sm-10 col-md-6">
            <form id="account" method="post">
                <h4>Use a local account to log in.</h4>
                <hr />
                <div class="form-group">
                    <label for="Input_Email">Email</label>
                    <input
                        class="form-control"
                        type="email"
                        id="Input_Email"
                        v-model="email"
                    />
                </div>
                <div class="form-group">
                    <label for="Input_Password">Password</label>
                    <input
                        class="form-control"
                        type="password"
                        id="Input_Password"
                        v-model="password"
                    />
                </div>
                <div class="form-group">
                    <button
                        @click="loginClicked($event)"
                        type="submit"
                        class="btn btn-primary"
                    >
                        Log in
                    </button>
                </div>
            </form>
        </div>
        <div class="col-sm-1 col-md-3"></div>
    </div>
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import store from "@/store/index"

@Options({
    components: {},
    props: {},
})
export default class Login extends Vue {
    email: string = "";
    password: string = "";

    async loginClicked(event: Event): Promise<void> {
        event.preventDefault();

        store.dispatch('logIn', { email: this.email, password: this.password });
    }
}
</script>
